name: GitHub Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Achievements Only
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-achievements.svg

          # ONLY achievements plugin enabled
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: |
            github-sponsor
            stargazer
