name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d-contrib

    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "3D Profile updated" || echo "No changes"
          git push
